Document: perl
Title: Debian perl Manual
Author: <insert document author here>
Abstract: This manual describes what perl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/perl/perl.sgml.gz

Format: postscript
Files: /usr/share/doc/perl/perl.ps.gz

Format: text
Files: /usr/share/doc/perl/perl.text.gz

Format: HTML
Index: /usr/share/doc/perl/html/index.html
Files: /usr/share/doc/perl/html/*.html
